### ISSUE TITLE
ブログ追加モーダル送信時のリセット

### ISSUE THREAD

**Issue by ohara95** [ohara95/blogFavo#15]
categoryとtagとpublicのリセットがされないのでリセットできるようにする

**Comment by Nozomuts** [comment]
やらせていただきます

**Comment by Nozomuts** [comment]
@ohara95 
react-hook-formでcheckboxの値はリセットされても、表示はリセットされないみたいです。categoryも取得はできましたが今のところ、AutoCompleteがある場合のリセット方法がわかってないです。モーダル閉じるとリセットされるみたいなので、送信時に閉じるようにした方が実装も簡単そうです

**Comment by ohara95** [comment]
@NozomuTsuruta 
送信時にモーダル閉じると連続で追加したい場合めんどくさいかなとおもって送信時リセットの実装が良かったんですけど取りあえず送信時にモーダル閉じる仕様でも大丈夫です！

**Comment by Nozomuts** [comment]
@ohara95 確かに使いにくそうですね、Inputほど再レンダリング起きないのでStateで管理して、リセットする方向で行きます。
ついでにDialogをrecoilで管理しようと思うのですがどうでしょうか？
Toastも別issueでrecoilで管理したいなと思ってます

**Comment by ohara95** [comment]
@NozomuTsuruta 
ダイアログをrecoilで管理👀やってみてもらってもいいですか？みたいです！
toastのrecoil管理了解です！
