### ISSUE TITLE
ファイル整理

### ISSUE THREAD

**Issue by ohara95** [ohara95/blogFavo#16]
atomicデザイン廃止

pagesディレクトリとcomponentsディレクトリを作成
全体的に使えるcomponentはcomponentsに格納
そのページでしか使用しないcomponentはpagesのcomponentsディレクトリに格納

**Comment by Nozomuts** [comment]
@ohara95 
pagesの下はアンダースコア以外ルーティングされる感じだったので、pagesのなかにcomponentsディレクトリを作ると、例えばbutton.tsxなら、`http://localhost:3000/components/button`に表示されてしまうかもしれません。
![image](https://user-images.githubusercontent.com/61049074/98231821-481caf80-1fa0-11eb-922c-3d2ca41cff19.png)

Next少し使った程度なので違ったらごめんなさいいい

**Comment by ohara95** [comment]
@NozomuTsuruta 
ご指摘ありがとうございます！
たしかにnextということを忘れてました(ﾟωﾟ)
しばし考えます、、！／(^o^)＼
