### ISSUE TITLE
ブログクリックで外部サイト表示

### ISSUE THREAD

**Issue by ohara95** [ohara95/blogFavo#18]
dbからurl取ってきてgetリクエストで画像と詳細を取ってくる
それを一覧に表示
https://tech.playground.style/javascript/fetch-api-data/
https://blog.katsubemakito.net/nodejs/request
https://blog.narumium.net/2020/10/01/next-js%E3%81%A7%E5%A4%96%E9%83%A8api%E3%82%92%E5%8F%A9%E3%81%8F%EF%BC%93%E3%81%A4%E3%81%AE%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3/

**Comment by ohara95** [comment]
やりかた全然わかんないので参考ブログ等あったら教えてください🙇‍♂️

**Comment by ohara95** [comment]
やり方わからないのでブログ等共有いただけると嬉しいです🙇‍♂️

**Comment by Nozomuts** [comment]
@ohara95 GithubAPIを使ってファイルを取得している感じな気がするので普通のブログサイトとかには使えなさそうですね知らんけど
いったんaタグで外部ページで開く感じにして、方法が見つかったら変える感じがいいかと
