### ISSUE TITLE
並び替え(ドラッグ&ドロップ)

### ISSUE THREAD

**Issue by ohara95** [ohara95/blogFavo#23]
リストとカテゴリー両方
react DnDですかね、、、

https://www.npmjs.com/package/react-dnd
https://qiita.com/mizchi/items/9a426af4fe919cd9d9d5

**Comment by Nozomuts** [comment]
使ったことないけど面白そうなのでやってみます！

**Comment by Nozomuts** [comment]
もう少しコンポーネント整理してからの方が良さげ

**Comment by Nozomuts** [comment]
@ohara95 思ったのですが、これ並び順がIDとかで決まってるわけじゃなくて、作成順や名前順とかになるので実装厳しい気がしてきました

**Comment by ohara95** [comment]
@NozomuTsuruta 
なるほど。。。
そしたらcloseしますね！
調べてくれてありがとうございました🙇‍♂️
