### ISSUE TITLE
twitterアカウントでの登録実装

### ISSUE THREAD

**Issue by ohara95** [ohara95/blogFavo#39]
twitterAPI取得？

**Comment by Nozomuts** [comment]
@ohara95 静的サイトジェネレータ使うなら、デプロイ先はvercelだと思うのですが、TwitterAPIを使うのにアプリのURLが必要でした。masterブランチをデプロイ対象にして、いったんデプロイしてみてもいいでしょうか？

**Comment by ohara95** [comment]
@NozomuTsuruta 
大丈夫です！ありがとうございます！

**Comment by Nozomuts** [comment]
@ohara95 すみません、自分のリポジトリじゃない場合クローンしたリポジトリをデプロイする感じになっちゃいそうなので、デプロイお願いしてもよろしいでしょうか？それかこのissueは後回しでもいいかもしれません

**Comment by ohara95** [comment]
@NozomuTsuruta 
なるほど！やってみます👀！

**Comment by ohara95** [comment]
@NozomuTsuruta 
deployしました！宜しくお願いします！
https://blog-favo.vercel.app/
